In [1]:
import numpy as np;import pandas as pd

In [2]:
df=pd.read_csv("./HR.csv")

In [3]:
sl_s=df["satisfaction_level"]

In [ ]:
sl_s.isnull()

In [ ]:
sl_s[sl_s.isnull()] #查看是否为空

In [ ]:
df[df["satisfaction_level"].isnull()]  

In [ ]:
sl_s=sl_s.dropna()

In [ ]:
sl_s.mean()

In [ ]:
sl_s.std()

In [ ]:
sl_s.max()

In [ ]:
sl_s.min()

In [ ]:
sl_s.median()

In [ ]:
sl_s.quantile(q=0.25)

In [ ]:
sl_s.quantile(q=0.75)

In [ ]:
sl_s.skew()

In [ ]:
sl_s.kurt()

In [ ]:
np.histogram(sl_s.values,bins=np.arange(0.0,1.1,0.1)) 

# 3-12

In [ ]:
le_s=df["last_evaluation"]

In [ ]:
le_s[le_s.isnull()]  # 表示没有空值

In [ ]:
le_s.std()

In [ ]:
le_s.mean()

In [ ]:
le_s.median()

In [ ]:
le_s.max()

In [ ]:
le_s.min()

In [ ]:
le_s.skew()

In [ ]:
le_s.kurt()

In [ ]:
le_s[le_s>1]

In [ ]:
le_s=le_s[le_s<=1]

In [ ]:
le_s=df["last_evaluation"]

In [ ]:
q_low=le_s.quantile(q=0.25)   #下四分位

In [ ]:
q_high=le_s.quantile(q=0.75)   #上四分位

In [ ]:
q_interval=q_high-q_low  # 四分位间数

In [ ]:
k=1.5

In [ ]:
le_s=le_s[le_s<q_high+k*q_interval][le_s>q_low-k*q_interval] # 上下界之间的为正常值 

In [ ]:
le_s

In [ ]:
le_s.count()

In [ ]:
len(le_s)

In [ ]:
np.histogram(le_s.values,bins=np.arange(0.0,1.1,0.1))  #直方

# 3-13

In [ ]:
np_s=df["number_project"]

In [ ]:
df[df["number_project"].isnull()]

In [ ]:
np_s.describe()

In [ ]:
np_s.skew()  # 略正偏

In [ ]:
np_s.kurt()

In [ ]:
np_s.value_counts()

In [ ]:
np_s.value_counts(normalize=True) #If True then the object returned will contain the relative frequencies of the unique values.

In [ ]:
np_s.value_counts(normalize=True).sort_index()

# 3-14

In [4]:
amh_s=df["average_monthly_hours"]

In [5]:
amh_s.describe()

count    15002.000000
mean       201.041728
std         49.941815
min         96.000000
25%        156.000000
50%        200.000000
75%        245.000000
max        310.000000
Name: average_monthly_hours, dtype: float64

In [6]:
amh_s.skew() #偏度

0.05322458779916304

In [7]:
amh_s.kurt() #峰度

-1.1350158577565719

判断异常值

In [8]:
amh_s=amh_s[amh_s<amh_s.quantile(0.75)+1.5*(amh_s.quantile(0.75)-amh_s.quantile(0.25))][amh_s>amh_s.quantile(0.25)-1.5*(amh_s.quantile(0.75)-amh_s.quantile(0.25))]

In [9]:
len(amh_s)

15002

In [10]:
amh_s.describe()

count    15002.000000
mean       201.041728
std         49.941815
min         96.000000
25%        156.000000
50%        200.000000
75%        245.000000
max        310.000000
Name: average_monthly_hours, dtype: float64

In [11]:
np.histogram(amh_s.values,bins=10)  #分布

(array([ 367, 1240, 2736, 1722, 1628, 1712, 1906, 2240, 1127,  324]),
 array([ 96. , 117.4, 138.8, 160.2, 181.6, 203. , 224.4, 245.8, 267.2,
        288.6, 310. ]))

In [12]:
np.histogram(amh_s.values,bins=np.arange(amh_s.min(),amh_s.max()+10,10))

(array([ 168,  171,  147,  807, 1153, 1234, 1075,  824,  818,  758,  751,
         738,  856,  824,  987, 1002, 1045,  935,  299,  193,  131,   86]),
 array([ 96, 106, 116, 126, 136, 146, 156, 166, 176, 186, 196, 206, 216,
        226, 236, 246, 256, 266, 276, 286, 296, 306, 316]))

In [13]:
amh_s.value_counts(bins=np.arange(amh_s.min(),amh_s.max()+10,10))

(146.0, 156.0]     1277
(136.0, 146.0]     1159
(256.0, 266.0]     1063
(236.0, 246.0]     1006
(156.0, 166.0]      995
(246.0, 256.0]      987
(126.0, 136.0]      886
(216.0, 226.0]      873
(266.0, 276.0]      860
(166.0, 176.0]      832
(226.0, 236.0]      814
(176.0, 186.0]      813
(186.0, 196.0]      761
(196.0, 206.0]      755
(206.0, 216.0]      731
(276.0, 286.0]      319
(95.999, 106.0]     187
(286.0, 296.0]      164
(116.0, 126.0]      162
(106.0, 116.0]      162
(296.0, 306.0]      128
(306.0, 316.0]       68
Name: average_monthly_hours, dtype: int64

# 3-15

In [16]:
tsc_s=df["time_spend_company"]

In [17]:
tsc_s.value_counts(normalize=True).sort_index()

2     3245
3     6445
4     2557
5     1473
6      718
7      188
8      162
10     214
Name: time_spend_company, dtype: int64

# 3-16

In [20]:
wa_s=df["Work_accident"]

In [21]:
wa_s.value_counts()

0    12833
1     2169
Name: Work_accident, dtype: int64

# 3-19

In [22]:
s_s=df['salary']

In [23]:
s_s.value_counts()

low       7318
medium    6446
high      1237
nme          1
Name: salary, dtype: int64

In [27]:
s_s.where(s_s!="nme").dropna()   #不满足where条件的会赋值为 NAN

0           low
1        medium
2        medium
3           low
4           low
          ...  
14996       low
14997       low
14998       low
14999       low
15000       low
Name: salary, Length: 15001, dtype: object

# 3-21 简单对比分析操作

In [28]:
df=df.dropna(axis=0,how='any')

In [30]:
df=df[df["last_evaluation"]<=1][df['salary']!='nme'][df['department']!='sale']

/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


In [31]:
df

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
0                        157                   3              0     1   
1                        262                   6              0     1   
2                        272                   4              0     1   
3                        223                   5              0     1   
4                        159                   3              0     1   
...                      ...                 ...            ...   ...   
14994                    151                   3              0     1   
14995                    160                   3              0     1   
14996                    143                   3              0     1   
14997                    280                   4              0     1   
14998                    158                   3              0     1   

       promotion_last_5years department  salary  
0                          0      sales     low  
1                          0      sales  medium  
2                          0      sales  medium  
3                          0      sales     low  
4                          0      sales     low  
...                      ...        ...     ...  
14994                      0    support     low  
14995                      0    support     low  
14996                      0    support     low  
14997                      0    support     low  
14998                      0    support     low  

[14999 rows x 10 columns]

In [32]:
df.groupby("department").mean()

satisfaction_level  last_evaluation  number_project  \
department                                                         
IT                     0.618142         0.716830        3.816626   
RandD                  0.619822         0.712122        3.853875   
accounting             0.582151         0.717718        3.825293   
hr                     0.598809         0.708850        3.654939   
management             0.621349         0.724000        3.860317   
marketing              0.618601         0.715886        3.687646   
product_mng            0.619634         0.714756        3.807095   
sales                  0.614447         0.709717        3.776329   
support                0.618300         0.723109        3.803948   
technical              0.607897         0.721099        3.877941   

             average_monthly_hours  time_spend_company  Work_accident  \
department                                                              
IT                      202.215974            3.468623       0.133659   
RandD                   200.800508            3.367217       0.170267   
accounting              201.162973            3.522816       0.125163   
hr                      198.684709            3.355886       0.120433   
management              201.249206            4.303175       0.163492   
marketing               199.385781            3.569930       0.160839   
product_mng             199.965632            3.475610       0.146341   
sales                   200.911353            3.534058       0.141787   
support                 200.758188            3.393001       0.154778   
technical               202.497426            3.411397       0.140074   

                 left  promotion_last_5years  
department                                    
IT           0.222494               0.002445  
RandD        0.153748               0.034307  
accounting   0.265971               0.018253  
hr           0.290934               0.020298  
management   0.144444               0.109524  
marketing    0.236597               0.050117  
product_mng  0.219512               0.000000  
sales        0.244928               0.024155  
support      0.248991               0.008973  
technical    0.256250               0.010294

In [35]:
df.loc[:,["last_evaluation","department"]].groupby("department").mean()

last_evaluation
department                  
IT                  0.716830
RandD               0.712122
accounting          0.717718
hr                  0.708850
management          0.724000
marketing           0.715886
product_mng         0.714756
sales               0.709717
support             0.723109
technical           0.721099

In [36]:
df.loc[:,["average_monthly_hours","department"]].groupby("department")["average_monthly_hours"].apply(lambda x:x.max()-x.min()) #极差

department
IT             212
RandD          210
accounting     213
hr             212
management     210
marketing      214
product_mng    212
sales          214
support        214
technical      213
Name: average_monthly_hours, dtype: int64