In [1]:
import numpy as np;import pandas as pd

In [2]:
df=pd.read_csv("./HR.csv")

In [3]:
sl_s=df["satisfaction_level"]

In [4]:
sl_s.isnull()

0        False
1        False
2        False
3        False
4        False
         ...  
14997    False
14998    False
14999     True
15000     True
15001    False
Name: satisfaction_level, Length: 15002, dtype: bool

In [9]:
sl_s[sl_s.isnull()] #查看是否为空

Series([], Name: satisfaction_level, dtype: float64)

In [6]:
df[df["satisfaction_level"].isnull()]  

satisfaction_level  last_evaluation  number_project  \
14999                 NaN             0.52               2   
15000                 NaN        999999.00               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
14999                    158                   3              0     1   
15000                    158                   3              0     1   

       promotion_last_5years department salary  
14999                      0    support    low  
15000                      0       sale    low

In [8]:
sl_s=sl_s.dropna()

In [10]:
sl_s.mean()

0.6128393333333333

In [11]:
sl_s.std()

0.24862338135944925

In [12]:
sl_s.max()

1.0

In [13]:
sl_s.min()

0.09

In [14]:
sl_s.median()

0.64

In [15]:
sl_s.quantile(q=0.25)

0.44

In [16]:
sl_s.quantile(q=0.75)

0.82

In [17]:
sl_s.skew()

-0.47643761717258093

In [18]:
sl_s.kurt()

-0.6706959323886252

In [19]:
np.histogram(sl_s.values,bins=np.arange(0.0,1.1,0.1)) 

(array([ 195, 1214,  532,  974, 1668, 2146, 1973, 2074, 2220, 2004]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))

# 3-12

In [23]:
le_s=df["last_evaluation"]

In [25]:
le_s[le_s.isnull()]  # 表示没有空值

Series([], Name: last_evaluation, dtype: float64)

In [69]:
le_s.std()

0.17118464250786233

In [27]:
le_s.mean()

67.37373216904412

In [68]:
le_s.median()

0.72

In [40]:
le_s.max()

1.0

In [39]:
le_s.min()

0.36

In [38]:
le_s.skew()

-0.02653253746872579

In [37]:
le_s.kurt()

-1.2390454655108427

In [36]:
le_s[le_s>1]

Series([], Name: last_evaluation, dtype: float64)

In [35]:
le_s=le_s[le_s<=1]

In [48]:
le_s=df["last_evaluation"]

In [49]:
q_low=le_s.quantile(q=0.25)   #下四分位

In [50]:
q_high=le_s.quantile(q=0.75)   #上四分位

In [51]:
q_interval=q_high-q_low  # 四分位间数

In [52]:
k=1.5

In [57]:
le_s=le_s[le_s<q_high+k*q_interval][le_s>q_low-k*q_interval] # 上下界之间的为正常值 

In [60]:
le_s

0        0.53
1        0.86
2        0.88
3        0.87
4        0.52
         ... 
14996    0.53
14997    0.96
14998    0.52
14999    0.52
15001    0.40
Name: last_evaluation, Length: 15001, dtype: float64

In [58]:
le_s.count()

15001

In [59]:
len(le_s)

15001

In [61]:
np.histogram(le_s.values,bins=np.arange(0.0,1.1,0.1))  #直方图

(array([   0,    0,    0,  179, 1390, 3396, 2234, 2062, 2752, 2988]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))

# 3-13

In [71]:
np_s=df["number_project"]

In [72]:
df[df["number_project"].isnull()]

Empty DataFrame
Columns: [satisfaction_level, last_evaluation, number_project, average_monthly_hours, time_spend_company, Work_accident, left, promotion_last_5years, department, salary]
Index: []

In [74]:
np_s.describe()

count    15002.000000
mean         3.802693
std          1.232733
min          2.000000
25%          3.000000
50%          4.000000
75%          5.000000
max          7.000000
Name: number_project, dtype: float64